# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Jack Fitzsimons
tagline:          'Machine Learning Researcher'
description:      'D.Phil. (Oxon) in Machine Learning '
url: https://jkfitzsimons.github.io
baseurl: https://jkfitzsimons.github.io

scholar:
  style: apa
  repository: assets/pdf
  bibliography_template: bibliography

author:
  name:           'Jack Fitzsimons'


gems: [jekyll-paginate,jekyll-gist,jekyll/scholar]
paginate:         5
paginate_path: "page:num"

# Custom vars
version:          1.0.0

github:
      repo:           https://github.com/jkfitzsimons/jkfitzsimons.github.io
